SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BB.CATEGORY, BB.SUM AS TOTAL_SALES 
FROM AUTHOR A
JOIN (
    SELECT B.AUTHOR_ID, B.CATEGORY, SUM(BS.TOTAL_SALES * B.PRICE) AS SUM
    FROM BOOK B
    JOIN (
        SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
        FROM BOOK_SALES 
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
        GROUP BY BOOK_ID
    ) BS ON BS.BOOK_ID = B.BOOK_ID
    GROUP BY B.AUTHOR_ID, B.CATEGORY
) BB ON BB.AUTHOR_ID = A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, BB.CATEGORY DESC;
