-- 코드를 입력하세요
SELECT PRODUCT_CODE,(PRICE * O.TOTAL) AS SALES FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT)AS TOTAL FROM OFFLINE_SALE GROUP BY 1) O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 2 DESC, 1 ASC