SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    -- ONLINE_SALE 테이블의 2022년 3월 데이터 선택
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022

    UNION ALL

    -- OFFLINE_SALE 테이블의 2022년 3월 데이터 선택
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022
) AS COMBINED_SALES
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;