-- 코드를 입력하세요

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES FROM REST_INFO R JOIN(
    SELECT
    FOOD_TYPE,
    MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC
) J
ON R.FOOD_TYPE = J.FOOD_TYPE AND R.FAVORITES = J.FAVORITES
ORDER BY FOOD_TYPE DESC
    