SELECT ID, CASE WHEN ROWNUM <= TOTAL * 0.25 THEN "LOW"
WHEN ROWNUM <= TOTAL * 0.5 THEN "MEDIUM"
WHEN ROWNUM <= TOTAL * 0.75 THEN "HIGH"
ELSE "CRITICAL"
END AS COLONY_NAME
FROM (SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY) ROWNUM FROM ECOLI_DATA) ECOLI_DATA,
(SELECT COUNT(*) AS TOTAL FROM ECOLI_DATA) TOTALECOLI
ORDER BY ID;

#SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY) ROWNUM FROM ECOLI_DATA;