-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS , RR.SCORE FROM REST_INFO RI,
(SELECT REST_ID, ROUND(SUM(REVIEW_SCORE) / COUNT(*),2) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) AS RR
WHERE RR.REST_ID = RI.REST_ID AND RI.ADDRESS LIKE '서울%'
ORDER BY RR.SCORE DESC, RI.FAVORITES DESC;