-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE)AS MONTH, GENDER, COUNT(U.GENDER) AS USERS FROM USER_INFO AS U
JOIN (SELECT USER_ID, SALES_DATE FROM ONLINE_SALE GROUP BY USER_ID, YEAR(SALES_DATE) , MONTH(SALES_DATE)) AS O
ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE) , MONTH(SALES_DATE), GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC