-- 코드를 작성해주세요

SELECT 
CASE
WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN CONCAT(1,'Q')
WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN CONCAT(2,'Q')
WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN CONCAT(3,'Q')
WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN CONCAT(4,'Q')
END AS QUARTER
, COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY 1