-- 코드를 입력하세요 생산일자가 2022 5월 식품들의 식품 아이디 이름 총매출 조회 오름차순
SELECT P.PRODUCT_ID, P.PRODUCT_NAME,P.PRICE * SUM(O.AMOUNT ) AS TOTAL_SALES FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID WHERE O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;