-- 코드를 입력하세요

# SELECT USER_ID, NICKNAME, TOTAL_SALES FROM(
# SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD AS B, USED_GOODS_USER AS U WHERE B.WRITER_ID = U.USER_ID AND B.STATUS = 'DONE' 
# ORDER BY TOTAL_SALES ASC) AS A
# HAVING TOTAL_SALES >= 700000

SELECT
u.USER_ID,
u.NICKNAME,
SUM(b.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY TOTAL_SALES;