SELECT 
    E.YEAR_DIFF AS YEAR, 
    (M.MAXSIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, 
    E.ID 
FROM 
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR_DIFF, 
        SIZE_OF_COLONY, 
        ID 
     FROM ECOLI_DATA) AS E
INNER JOIN 
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR_DIFF, 
        MAX(SIZE_OF_COLONY) AS MAXSIZE 
     FROM ECOLI_DATA 
     GROUP BY YEAR(DIFFERENTIATION_DATE)) AS M ON E.YEAR_DIFF = M.YEAR_DIFF
ORDER BY E.YEAR_DIFF ASC, YEAR_DEV ASC;
