SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F
INNER JOIN FISH_NAME_INFO AS N ON F.FISH_TYPE = N.FISH_TYPE
WHERE F.LENGTH = (
    SELECT MAX(FI.LENGTH)
    FROM FISH_INFO FI
    WHERE FI.FISH_TYPE = F.FISH_TYPE AND FI.LENGTH > 10
)
ORDER BY F.ID ASC;
